#!/bin/sh

revision=1
version="$(. "${base_dir}/host-recipes/gcc/recipe" && echo ${version})"

hostdeps="gcc pkg-config"
imagedeps="build-essential"
deps="mlibc-headers"

package() {
    cd "${build_dir}"/host-builds/gcc/build
    make install-target-libgcc DESTDIR="${dest_dir}"
}
