#!/bin/sh

revision=1
version=455862c27d4ace91765080c705f766a9d7a3966f
git_url="https://github.com/CascadeOS/mlibc.git"
commit="$version"

hostdeps="binutils gcc pkg-config"
builddeps="freestnd-c-hdrs freestnd-cxx-hdrs frigg libsmarter"
deps="mlibc-headers libcascade libgcc"

configure() {
    # pkg-config strips /usr/include and /usr/lib but as we compile with -nostdinc
    # we need to prevent these paths from being stripped
        PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 \
        PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 \
    meson_configure -Ddefault_library=static -Dno_headers=true
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install
}
