#!/bin/sh

revision=1
version=6.3.1
git_url="https://github.com/CascadeOS/mlibc.git"
commit="0cd1f55cc4bf53a2ad321d5df43e292f9da2efdd"
source_allow_network=yes

hostdeps="binutils gcc pkg-config"
builddeps="freestnd-c-hdrs freestnd-cxx-hdrs frigg libsmarter"
deps="mlibc-headers libgcc"

prepare() {
    meson subprojects download
}

configure() {
    # pkg-config strips /usr/include and /usr/lib but as we compile with -nostdinc
    # we need to prevent these paths from being stripped
        PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 \
        PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 \
    meson_configure -Dno_headers=true
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install
}
