#!/bin/sh

revision=1
version=6.3.1
git_url="https://github.com/CascadeOS/mlibc.git"
commit="ee6650a2d009acd9792b8e6589ae46fffea76745"
source_allow_network=yes

hostdeps="binutils gcc pkg-config"
imagedeps="libmpc-dev"
deps="mlibc-headers libgcc"

prepare() {
    meson subprojects download
}

configure() {
    meson_configure -Dno_headers=true
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install
}
