#!/bin/sh

revision=1
version=8.3
tarball_url="https://ftp.gnu.org/gnu/readline/readline-${version}.tar.gz"
tarball_blake2b="45d6fe7e34c56d309102a94aa776a7f5284201e844450e14ff818df9fa84a72154bdca70f11828c94954b080cbbe4666fa0b00ffa8460118ec8f3ea551b73dad"

hostdeps="gcc pkg-config"
deps="core-libs ncurses"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-curses
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"
}
