#!/bin/sh

revision=1
version=1.19
tarball_url="https://ftp.gnu.org/pub/gnu/libiconv/libiconv-${version}.tar.gz"
tarball_blake2b="a77d5190bfed76627ac5abf24b90a19f3f1c460f2fe4e5002bb4799d789236c268dff0693aa9836ab12df76b1381084dbe2b78cabe8221eb97f54e14a210a8e2"

hostdeps="gcc pkg-config"
deps="mlibc libgcc libstdc++"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-extra-encodings
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"

    mkdir -p "${dest_dir}${prefix}/lib/pkgconfig"
    cat >"${dest_dir}${prefix}/lib/pkgconfig/libiconv.pc" <<EOF
prefix=${prefix}
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: libiconv
Description: International text conversion library
Version: ${version}
Libs: -L\${libdir} -liconv
Cflags: -I\${includedir}
EOF
}
