#!/bin/sh

revision=1
version=1.19
tarball_url="https://ftp.gnu.org/pub/gnu/libiconv/libiconv-${version}.tar.gz"
tarball_sha256="88dd96a8c0464eca144fc791ae60cd31cd8ee78321e67397e25fc095c4a19aa6"

hostdeps="gcc pkg-config"
deps="mlibc libgcc libstdc++"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-extra-encodings
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"

    mkdir -p "${dest_dir}${prefix}/lib/pkgconfig"
    cat >"${dest_dir}${prefix}/lib/pkgconfig/libiconv.pc" <<EOF
prefix=${prefix}
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: libiconv
Description: International text conversion library
Version: ${version}
Libs: -L\${libdir} -liconv
Cflags: -I\${includedir}
EOF
}
