#!/bin/sh

revision=1
version=0.0.3
git_url="https://github.com/CascadeOS/c-libcascade.git"
commit="f567bfc641d2762c3283995f3e65167cb5410c3f"
source_dir="recipes/libcascade/src"

hostdeps="binutils gcc pkg-config"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install
}
