#!/bin/sh

revision=1
version=0.0.3
git_url="https://github.com/CascadeOS/c-libcascade.git"
commit="b19637ec128d30083b67cc9b6fb028d5d2017496"
source_dir="recipes/libcascade/src"

hostdeps="binutils gcc pkg-config"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install
}
