#!/bin/sh

revision=1
version=1.3.2
tarball_url="https://github.com/madler/zlib/archive/refs/tags/v${version}.tar.gz"
tarball_sha256="b99a0b86c0ba9360ec7e78c4f1e43b1cbdf1e6936c8fa0f6835c0cd694a495a1"

hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cp -rT "${source_dir}" .

    CC="${OS_TRIPLET}-gcc" \
    AR="${OS_TRIPLET}-ar" \
    RANLIB="${OS_TRIPLET}-ranlib" \
    CFLAGS="${TARGET_CFLAGS}" \
    ./configure \
        --prefix=${prefix} \
        --static
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"
}
