#!/bin/sh

revision=1
version=1.3.2
tarball_url="https://github.com/madler/zlib/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="21bcccda24d5868b9268e9f7a0fb125ff284cd07f8c708c021dd2702a48852447d4b1bc1e64480cf4d04539ef1ae99225fbde4f63894727a5edcfcd00f21c5e9"

hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cp -rT "${source_dir}" .

    CC="${OS_TRIPLET}-gcc" \
    AR="${OS_TRIPLET}-ar" \
    RANLIB="${OS_TRIPLET}-ranlib" \
    CFLAGS="${TARGET_CFLAGS}" \
    ./configure \
        --prefix=${prefix} \
        --static
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"
}
