#!/bin/sh

revision=1
version=1.0
tarball_url="https://ftpmirror.gnu.org/gnu/gettext/gettext-${version}.tar.gz"
tarball_blake2b="1e4b78979f780878472142f1c0baba468d60f4b5605eeb5db5c092901183e3128c79df94c2041de870920f079b4bf38e6dae056b731e4b2b4c5cc343940962d8"

hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"

    rm -fv "${dest_dir}${prefix}"/lib/libintl* \
           "${dest_dir}${prefix}"/lib/preloadable_libintl* \
           "${dest_dir}${prefix}"/include/libintl.h
}
