#!/bin/sh

revision=1
version=3.12
tarball_url="https://ftp.gnu.org/gnu/grep/grep-${version}.tar.xz"
tarball_blake2b="93d06bce04793f4b4c94d92febc6092f669e50e1bfc1bef3c911a2ca322560bdab8619e88a05a4d6ea4908b2d01da1926a99a22eecc513bd48b8957984bdfa12"

hostdeps="gcc pkg-config"
deps="core-libs pcre2"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism} SUBDIRS="po lib doc src tests"
}

package() {
    make install DESTDIR="${dest_dir}" SUBDIRS="po lib doc src tests"
}
