#!/bin/sh

revision=1
version=2.5.1
tarball_url="https://distfiles.ariadne.space/pkgconf/pkgconf-${version}.tar.xz"
tarball_blake2b="0995c1d649876d27e9275a77b702c0c100979c7b83fb7b58c925ca287be5e1568dd7ae2781dac51beb9e84a41d4424428f0542e4de488c45d005d602e76e1277"

imagedeps="build-essential"

configure() {
        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
    "${source_dir}"/configure \
        --prefix="${prefix}"
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
    mkdir -p ${dest_dir}${prefix}/share/pkgconfig/personality.d

    cat >${dest_dir}${prefix}/share/pkgconfig/personality.d/${OS_TRIPLET}.personality <<EOF
Triplet: ${OS_TRIPLET}
SysrootDir: ${sysroot}
DefaultSearchPaths: ${sysroot}/usr/lib/pkgconfig:${sysroot}/usr/share/pkgconfig
SystemIncludePaths: ${sysroot}/usr/include
SystemLibraryPaths: ${sysroot}/usr/lib
EOF

    ln -s pkgconf ${dest_dir}${prefix}/bin/${OS_TRIPLET}-pkg-config
}
