#!/bin/sh

revision=1
version=1.15.1
tarball_url="https://ftpmirror.gnu.org/gnu/automake/automake-${version}.tar.gz"
tarball_sha256="988e32527abe052307d21c8ca000aa238b914df363a617e38f4fb89f5abf6260"

hostdeps="autoconf"
imagedeps="build-essential"

prepare() {
    autotools_recursive_regen
}

configure() {
        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
    "${source_dir}"/configure \
        --prefix="${prefix}"
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
}
