#!/bin/sh

revision=1
version=2.46.0
tarball_url="https://ftpmirror.gnu.org/gnu/binutils/binutils-${version}.tar.xz"
tarball_blake2b="9f4fd8897d237eb5003bdf439537dfc5f8c681e9ff939fb06bb8235ed298031ea4cc91611edb640ffc432199d5791289d003fe0d07acce80327dc40595a5eb9e"

source_hostdeps="autoconf automake"
imagedeps="build-essential"

prepare() {
    (cd ld && automake)
}

configure() {
        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
    ${source_dir}/configure \
        --target=${OS_TRIPLET} \
        --prefix=${prefix} \
        --with-sysroot=${sysroot} \
        --disable-werror \
        --enable-default-execstack=no
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
}
