#!/bin/sh

revision=1
version=5.3
tarball_url="https://ftp.gnu.org/gnu/bash/bash-${version}.tar.gz"
tarball_blake2b="82d1b54322bbd1e8c2a93380f1b2888a42a1d7186e504f41cee705a0fdd41463d8f20baa1755051e1396192f8ebd089524767d933a9e0b5fb76f2588601539bb"

hostdeps="gcc pkg-config"
imagedeps="build-essential"
deps="core-libs ncurses readline"

prepare() {
    autotools_recursive_regen
}

configure() {
    bash_cv_func_sigsetjmp=missing \
    autotools_configure \
        LDFLAGS="-Wl,--allow-multiple-definition" \
        CFLAGS="$TARGET_CFLAGS \
            -DDEFAULT_PATH_VALUE='\"/usr/local/sbin:/usr/local/bin:/usr/bin\"' \
            -DSTANDARD_UTILS_PATH='\"/usr/bin\"' \
            -DSYS_BASHRC='\"/etc/bash.bashrc\"' \
            -DSYS_BASH_LOGOUT='\"/etc/bash.bash_logout\"' \
            -DNON_INTERACTIVE_LOGIN_SHELLS \
        " \
        --with-curses \
        --enable-readline \
        --without-bash-malloc \
        --with-installed-readline
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"

    ln -sv bash "${dest_dir}${prefix}/bin/sh"
    ln -sv bash "${dest_dir}${prefix}/bin/rbash"
}
