#!/bin/sh

revision=1
version=15.2.0
tarball_url="https://ftpmirror.gnu.org/gnu/gcc/gcc-${version}/gcc-${version}.tar.xz"
tarball_blake2b="e270320978ca690e6e8f5ef06414dc13caf561f16403a3783c76fbf3dcee57e755a2d5bba922bf7fcae0bb6120443755d819b003791ae823d54589dd799804de"
clean_workdirs=no

imagedeps="build-essential libmpfr-dev libgmp-dev"
source_hostdeps="autoconf automake"
hostdeps="pkg-config"
hostrundeps="binutils"
deps="mlibc-headers"

prepare() {
    autotools_recursive_regen
    (cd libstdc++-v3 && autoconf)
}

configure() {
    mkdir -p build && cd build

        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        CFLAGS_FOR_TARGET="$TARGET_CFLAGS" \
        CXXFLAGS_FOR_TARGET="$TARGET_CXXFLAGS" \
    ${source_dir}/configure \
        --prefix="${prefix}" \
        --target=${OS_TRIPLET} \
        --with-sysroot="${sysroot}" \
        --enable-languages=c,c++ \
        --enable-threads=posix \
        --disable-multilib \
        --enable-shared \
        --enable-host-shared
}

build() {
    cd build
    make all-gcc all-target-libgcc -j${parallelism}
}

package() {
    cd build
    DESTDIR="${dest_dir}" make install-gcc install-target-libgcc
}
