#!/bin/sh

revision=1
version=b0dbea66bc19f7c5546f0039a3be842feb02678c
tarball_url="https://github.com/managarm/frigg/archive/${version}.tar.gz"
tarball_blake2b="0afd454fa50850c7ff0fca18b4f3aa18f79c27c72cc80684575b5a6dbbb245e10e92ace70dfddb6ec46f1ff9c0b5b740ab8429c15dd0e2b5aeeae1f45a6626e8"

configure() {
    meson_configure -Dbuild_tests=disabled
}

package() {
    DESTDIR="${dest_dir}" meson install
}
